/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./../components/common/ArticleCard.vue')['default']
    FareTabs: typeof import('./../components/ticket/FareTabs.vue')['default']
    FlightTripCard: typeof import('./../components/ticket/FlightTripCard.vue')['default']
    FloatingBack: typeof import('./../components/common/FloatingBack.vue')['default']
    LoginPrompt: typeof import('./../components/LoginPrompt.vue')['default']
    TrainTripCard: typeof import('./../components/ticket/TrainTripCard.vue')['default']
    TripCard: typeof import('./../components/ticket/TripCard.vue')['default']
  }
}
