/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/home/index" |
  "/pages/community/index" |
  "/pages/community/publish" |
  "/pages/community-detail/index" |
  "/pages/login/index" |
  "/pages/login/phone" |
  "/pages/more/index" |
  "/pages/order/index" |
  "/pages/profile/index" |
  "/pages/profile-edit/index" |
  "/pages/settings/index" |
  "/pages/ticket/choose" |
  "/pages/ticket/list" |
  "/pages/ticket/submit" |
  "/pages/traffic/index" |
  "/pages/trip/index" |
  "/pages/settings/security/index" |
  "/pages/ticket/passenger/add" |
  "/pages/ticket/passenger/select" |
  "/pages-fg/404/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
